templates:
  - templateName: mrfriendly
    logoPath: A:\\code\\invoirc-pdf\\bin\\templates\\mrfriendly\\logo.png
    langPacks: A:\\code\\invoicr-pdf\\bin\\langs

apiKeys:
- "aaaa"
outDir: A:\\code\\invoicr-pdf\\bin\\out
